name             'chef-haclusters'
maintainer       'PE, pf.'
maintainer_email 'philippe.eychart@mail.pf'
license          'GNU Public License 3.0'
description      'Installs/Configures chef-haclusters'
long_description 'Installs/Configures chef-haclusters'
version          '0.1.0'
depends          'haproxy'
depends          'chef-nodeAttributes'

